sudo: required

language: node_js

node_js:
  - "8"

services:
  - docker

stages:
  - build
  - tag

env:
  - PRIVATE_IMAGE="$PRIVATE_DOCKER_REGISTRY/admin-panel-client" \
    IMAGE="fairdata/admin-panel-client" \
    IMAGE_TAG="$PRIVATE_IMAGE:$TRAVIS_COMMIT" \
    IMAGE_TAG_BRANCH="$PRIVATE_IMAGE:"`echo $TRAVIS_BRANCH | sed 's#/#-#g'` \
    IMAGE_TAG_DEVELOP="$IMAGE:develop" \
    IMAGE_TAG_LATEST="$IMAGE:latest"

install:
  - npm install

cache:
  directories:
    - node_modules

before_script:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
  - docker login -u "$PRIVATE_DOCKER_USER" -p "$PRIVATE_DOCKER_PASSWORD" "$PRIVATE_DOCKER_REGISTRY"

jobs:
  include:
    - stage: build
      script:
        - npm run build
        - docker build -t $IMAGE_TAG .
        - docker push $IMAGE_TAG

    - stage: tag
      if: (branch = develop) AND (NOT (type IN (pull_request)))
      install: skip
      script:
        - docker pull $IMAGE_TAG
        - docker image tag $IMAGE_TAG $IMAGE_TAG_DEVELOP
        - docker push $IMAGE_TAG_DEVELOP

    - stage: tag
      if: (branch = master) AND (NOT (type IN (pull_request)))
      install: skip
      script:
        - docker pull $IMAGE_TAG
        - docker image tag $IMAGE_TAG $IMAGE_TAG_LATEST
        - docker push $IMAGE_TAG_LATEST

    - stage: tag
      if: (type = push)
      install: skip
      script:
        - docker pull $IMAGE_TAG
        - docker image tag $IMAGE_TAG $IMAGE_TAG_BRANCH
        - docker push $IMAGE_TAG_BRANCH
